#! /usr/bin/env bash
#
# https://tex.stackexchange.com/questions/1460/script-to-automate-externalizing-tikz-graphics#1475
# https://tex.stackexchange.com/questions/83992/how-to-create-and-include-tikz-files-in-your-manuscript
# https://stackoverflow.com/questions/2701902/standalone-diagrams-with-tikz
# http://www.hackenberger.at/blog/ktikz-editor-for-the-tikz-language/
#
#
# Additional code can be passed as follows:
#
#   tikz -i <(echo '\let\code\lstinline') example.tikz
#
#
# TODO
# * Provide option use different output directory
#

class='standalone'
classopts='tikz,border=0.5cm'
packages=()
tikzlibs=()
inputs=()
debug=false
while getopts 'c:C:p:l:i:d' opt; do
	case "$opt" in
		c)
			class=$OPTARG
			classopts=
			packages+=( $'\n'"\\usepackage{tikz}" )
			;;
		C)
			classopts=$OPTARG
			;;
		p)
			packages+=( $'\n'"\\usepackage{$OPTARG}" )
			;;
		l)
			tikzlibs+=( $'\n'"\\usetikzlibrary{$OPTARG}" )
			;;
		i)
			inputs+=( $'\n'"\\input{$OPTARG}" )
			;;
		d)
			debug=true
			;;
		h|\?)
			echo "usage: $(basename "$0")" \
				"[-c documentclass [-C classoptions]]" \
				"[-p package]" \
				"[-l tikzlibrary]" \
				"[-i \input]" \
				"[-d]" \
				"<file>.tikz"
			exit
			;;
	esac
done
shift $((OPTIND -1))

if $debug; then
	cat <<-LATEX
	\documentclass[$classopts]{$class}
	${packages[@]}
	${tikzlibs[@]}
	${inputs[@]}
	\begin{document}
		\input{$1}
	\end{document}
	LATEX
	exit
fi

if [ ! -f "$1" ]; then
	echo "File does not exist: $1" >&2
	exit 1
fi

name=${1%.tikz}
mkdir -p "$name"

pdflatex -jobname "$name" -output-directory "$name" <<LATEX
\documentclass[$classopts]{$class}
${packages[@]}
${tikzlibs[@]}
${inputs[@]}
\begin{document}
	\input{$1}
\end{document}
LATEX

